apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.deploy.application.name }}
  namespace: {{ .Values.deploy.application.namespace }}
  labels:
    name:  {{ .Values.deploy.application.name }}
    app: {{ .Values.deploy.application.name }}
spec:
  {{- if .Values.deploymentStrategy }}
  strategy:
{{ toYaml .Values.deploymentStrategy | indent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.deploy.application.name }}
  template:
    metadata:
      labels:
        name:  {{ .Values.deploy.application.name }}
        app: {{ .Values.deploy.application.name }}
      {{- if .Values.deploy.deploymentAnnotations }}
      annotations:
{{ toYaml .Values.deploy.deploymentAnnotations | indent 8 }}
  {{- end }}
    spec:
    {{- if .Values.serviceaccount }}
      serviceAccountName: {{ .Values.serviceaccount.serviceAccountName }}
    {{- end }}
      containers:
      - image: {{ .Values.deploy.images.repogistory }}/{{ .Values.deploy.images.name }}:{{ .Values.deploy.images.tag }}
        name:  {{ .Values.deploy.application.name }}
{{- if .Values.livenessProbe.enabled }}
        {{- if .Values.deploy.command }}
        command: {{ toYaml .Values.deploy.command | nindent 10 }}
        {{- end }}
        {{- if .Values.deploy.args }}
        args: {{ toYaml .Values.deploy.args | nindent 10 }}
        {{- end }}
        livenessProbe: 
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.deploy.application.port }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
{{ end }}
{{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: {{ .Values.deploy.application.port }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
{{- end }}        
        resources: 
{{- toYaml .Values.deploy.resources | nindent 10 }}
{{- if .Values.volume.enabled }}
        volumeMounts:
        {{- if .Values.volume.extraVolumeMounts }}{{ toYaml .Values.volume.extraVolumeMounts | trim | nindent 10 }}{{ end }}
{{- end }}
        ports:
        - containerPort:  {{ .Values.deploy.application.port }}
        imagePullPolicy: {{ .Values.deploy.images.pullPolicy }}
      nodeSelector:
        environment: {{ .Values.nodeSelector.environment }}
        role: apps
{{- if .Values.volume.enabled }}
      volumes:
      {{- if .Values.volume.extraVolumes  }}{{ toYaml .Values.volume.extraVolumes | trim | nindent 8 }}{{ end }}
{{- end }}
      imagePullSecrets:
        - name: {{ .Values.deploy.images.pullSecret }}
      restartPolicy: Always