apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploy.application.name }}
  namespace: {{ .Values.deploy.application.namespace }}
spec:  
  selector:
    app:  {{ .Values.deploy.application.name }}
  type:  {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port:  {{ .Values.service.port }}
    targetPort:  {{ .Values.deploy.application.port }}

